---
fixtures:
  repositories:
    auditd:
      repo: https://github.com/simp/pupmod-simp-auditd
      ref: 7.0.1
    iptables:
      repo: https://github.com/simp/pupmod-simp-iptables
      ref: 6.0.1
    pki:
      repo: https://github.com/simp/pupmod-simp-pki
      ref: 6.0.0
    simp_options:
      repo: https://github.com/simp/pupmod-simp-simp_options
      ref: 1.0.1
    simplib:
      repo: https://github.com/simp/pupmod-simp-simplib
      ref: 3.3.1
    stdlib:
      repo: https://github.com/simp/puppetlabs-stdlib
      ref: 4.13.1
    svckill:
      repo: https://github.com/simp/pupmod-simp-svckill
      ref: 3.2.0
    gitlab:
      repo: https://github.com/simp/puppet-gitlab
      ref: v1.13.3
  symlinks:
    simp_gitlab: "#{source_dir}"
